---
title: "Adding in the RNA"
output: html_document
---

```{r}
library(tidyverse)
```


```{r}
RNAdata <- read_csv("../analyses/20180524_RNA.csv")
```


```{r}
RNAdata
```




```{r}
left_join(prim_master, PCR_day01, by ="FRP") %>%
  left_join(PCR_day26, by ="FRP") %>%
  left_join(day9RNA, by ="FRP") %>%
  left_join(day12RNA, by ="FRP") %>%
  left_join(day26RNA, by ="FRP") 
```




```{r}
day9RNA <- RNAdata %>% mutate(record_id = row_number()) %>% 
  group_by(FRP) %>% 
  spread(Sample_Day, RNA_conc) %>% 
  rename(RNAday9 = "9", RNAday12 = "12", RNAday26 = "26" ) %>% 
  filter(RNAday9 != 0) %>% 
  select(FRP, infection_status, temperature_treatment, RNAday9)

```

```{r}
day12RNA <- RNAdata %>% mutate(record_id = row_number()) %>% 
  group_by(FRP) %>% 
  spread(Sample_Day, RNA_conc) %>% 
  rename(RNAday9 = "9", RNAday12 = "12", RNAday26 = "26" ) %>% 
  filter(RNAday12 != 0) %>% 
  select(FRP, RNAday12)

```

```{r}
day26RNA <- RNAdata %>% mutate(record_id = row_number()) %>% 
  group_by(FRP) %>% 
  spread(Sample_Day, RNA_conc) %>% 
  rename(RNAday9 = "9", RNAday12 = "12", RNAday26 = "26" ) %>% 
  filter(RNAday26 != 0) %>%
  select(FRP, RNAday26)

```


```{r}
day9RNA
```




```{r}
left_join(prim_master, PCR_day01, by ="FRP") %>%
  left_join(PCR_day26, by ="FRP") %>%
  left_join(day9RNA, by ="FRP") %>%
  left_join(day12RNA, by ="FRP") %>%
  left_join(day26RNA, by ="FRP") 
```





```{r}
left_join(prim_master, PCR_day01, by ="FRP") %>%
  left_join(PCR_day26, by ="FRP") %>%
  left_join(day9RNA, by ="FRP") %>%
  left_join(day12RNA, by ="FRP") %>%
  left_join(day26RNA, by ="FRP") %>%
  filter(RNAday9 > 0 | RNAday12 > 0 | RNAday26 > 0)
```


```{r}
master88 <- left_join(prim_master, PCR_day01, by ="FRP") %>%
  left_join(PCR_day26, by ="FRP") %>%
  left_join(day9RNA, by ="FRP") %>%
  left_join(day12RNA, by ="FRP") %>%
  left_join(day26RNA, by ="FRP") %>%
  filter(RNAday9 > 0 | RNAday12 > 0 | RNAday26 > 0)
```



```{r}
write_csv(master88, "../analyses/master88.csv")
```

